---
name: Component Issue
description: Report an issue related to a specific service/component
title: "[Component] <short description>"
labels: ["triage"]
assignees: []

body:
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Select the component or service this issue relates to.
      options:
        - auth-service
        - vm-builder
        - edge-router
        - infra
        - shared-db
        - other
      default: 5  # Index of "other" (starts at 0)

  - type: checkboxes
    id: backoffice
    attributes:
      label: Affected Subcomponents
      description: Select all subcomponents involved in this issue.
      options:
        - label: engine
        - label: directory
        
  - type: checkboxes
    id: edge
    attributes:
      label: Affected Subcomponents Edge
      description: Select all subcomponents involved in this issue.
      options:
        - label: poller
        - label: observability
        
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the problem or request in detail.
      placeholder: Describe what’s happening, expected behavior, and any relevant context.
---
