name: CI-CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installing SDK .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Tests
        run: dotnet test --no-build --verbosity n
      - name: Publish
        run: dotnet publish -c Release --self-contained --no-restore --no-build --nologo -p:PublishTrimmed=true --output publish
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: publish/
        with:
          files: |
            *.dll
            *.exe
            *.runtimeconfig.json
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}