name: CI-CD

on: push

env:
  APPLICATION_NAME: mysuperapp
jobs:
  # build:
  #   name: Build and Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Installing SDK .NET
  #       uses: actions/setup-dotnet@v1
  #       with:
  #         dotnet-version: 5.0.x
  #     - name: Restore
  #       run: dotnet restore
  #     - name: Build
  #       run: dotnet build --no-restore -c Release
  #     - name: Tests
  #       run: dotnet test --no-build --verbosity n
  release:
    name: Publish and Create Release
    if: startsWith(github.ref, 'refs/tags/')
    # needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            rid: win-x64
            archive: win-x64
          - os: ubuntu-latest
            rid: linux-x64
            archive: linux-x64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installing SDK .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Publish
        run: dotnet publish src/Cli -c Release --self-contained --nologo -p:PublishTrimmed=true --output publish -r ${{ matrix.rid }}
      - name: Create filename
        run: echo "FILENAME=${{env.APPLICATION_NAME}}.${ matrix.rid }.zip" >> $GITHUB_ENV
      - name: Pack artifacts
        uses: papeloto/action-zip@v1
        with:
          dest: ${{ env.FILENAME }}
          files: publish/
      - name: Github Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"  
      - name: Upload artifcat
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILENAME }}
          path: .
      #- name: Create Release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    files: ${{ matrix.archive }}.zip
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    name: Publish releases to github
    runs-on: self-hosted
    needs: 
      - release
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
    
    
    
