name: Build Dockerfile Action

on:
  workflow_call:
    inputs:
      dockerfile_context:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      name_suffix:
        required: true
        type: string
        
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ env.TAG_PREFIX }}
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.3.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ inputs.name_suffix }}
        tags: |
          type=match,pattern=${{ env.TAG_PREFIX }}(.*),group=1
          type=edge,branch=master
          type=sha
          type=ref,event=tag
          type=ref,event=pr
  
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: ${{ inputs.dockerfile_context }}
        file: ${{ inputs.dockerfile_path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
