name: "Push release to Octopus"

on:
  workflow_dispatch:
jobs:  
  publish:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: Show data
        run: |
          echo "${{ toJson(github) }}"
          echo "----"
      - name: Get the version
        run: echo "TAG=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: "vestas-power-solutions/test"
          tag: "${{env.TAG}}"
          fileName: "*"
