name: "Push release to Octopus"

on:
  workflow_dispatch:
  release:
    types: 
      - published

jobs:  
  publish:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: Show data
        run: |
          echo "${{ toJson(github) }}"
          echo "----"
