name: Image Builds

on:
  workflow_dispatch:
  push:
    #branches: 
    #  - master
    tags: 
      - 'backoffice/*'
    #paths:
    #  - 'src/**'
  #pull_request:
  #  paths:
  #    - 'src/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: web

jobs:
  build-and-test:
    name: Verifying build
    uses: ./.github/workflows/build.yaml
  web:
    name: Web
    needs: build-and-test
    uses: ./.github/workflows/container-action.yaml
    with:
      dockerfile_context: src/web
      dockerfile_path: src/web/Dockerfile
      name_suffix: bo
      tag_prefix: backoffice/
    secrets: inherit

  deploy-01-dev:
    name: Deploy to Development
    needs: 
      - web
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Validate if we are running a tag
        run: |
          if [[ "${ GITHUB_REF} " != refs/tags/* ]]; then
            echo "We need a tag to ensure we are deploying working services. Aborting workflow..."
            exit 1
          fi
      - name: Set IMAGE_TAG
        run: |
          TAG_NAME=${ GITHUB_REF#refs/tags/ }
          IMAGE_TAG=$(echo $TAG_NAME) | sed -E 's/backoffice\/(.*)/\1/')
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - run: echo ${{ env.IMAGE_TAG }}
      - run: "echo dev"
          

  deploy-02-stg:
    name: Deploy to Staging
    needs: 
      - deploy-01-dev
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: "echo stg"

  deploy-03-prd:
    name: Deploy to Production
    needs: 
      - deploy-02-stg
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: "echo prd"
